version: '3.8'

services:
  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - /var/www/portfolio/Portfolio:/app
    command: npm run serve:ssr  # Or "node dist/Portfolio/server/main.js"
    ports:
      - "4000:4000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - /var/www/portfolio/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    restart: unless-stopped

