version: '3.8'

services:
  json-server:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - /var/www/Portfolio/Portfolio:/app
    command: npx json-server --watch db.json --port 3000
    ports:
      - "3000:3000"
    restart: unless-stopped

  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - /var/www/Portfolio/Portfolio/dist/Portfolio:/app/dist/Portfolio
    command: node dist/Portfolio/server/server.mjs
    ports:
      - "443:443"  # Node.js listens on 4000
    environment:
      - NODE_ENV=production
      - PORT=443
    restart: unless-stopped

#  nginx:
#    image: nginx:alpine
#    ports:
#      - "80:80"
#      - "443:443"
#    volumes:
#      - /etc/letsencrypt:/etc/letsencrypt
#      - ./nginx.conf:/etc/nginx/conf.d/default.conf
#    depends_on:
#      - node
#    restart: unless-stopped
