version: '3.8'

services:
  node:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - /var/www/Portfolio/Portfolio:/app  # Maps your project root to /app
    command: npm run start
    ports:
      - "4000:4000"
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - /var/www/Portfolio/Portfolio/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - node
    restart: unless-stopped

  json-server:
    image: node:20-alpine
    working_dir: /app
    volumes:
      - /var/www/portfolio/Portfolio/db.json:/app/db.json  # Mount your db.json file
    command: npx json-server --host 0.0.0.0 --watch db.json
    ports:
      - "3000:3000"  # Expose json-server on port 3000
    restart: unless-stopped
