server {
    listen 80;
    server_name sanderworks.be www.sanderworks.be;
    return 301 https://$server_name$request_uri;
}


server {
    listen 443 ssl;
    server_name sanderworks.be www.sanderworks.be;

    ssl_certificate /etc/letsencrypt/live/sanderworks.be/fullchain.pem;
    ssl_certificate_key /etc/letsencrypt/live/sanderworks.be/privkey.pem;

    location / {
        proxy_pass http://node:4000;  # Proxy to Node.js container
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
    # Proxy API requests to json-server
    location /api {
        proxy_pass http://json-server:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection 'upgrade';
        proxy_set_header Host $host;
        proxy_cache_bypass $http_upgrade;
    }
}



