name: Deploy Portfolio

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install
        working-directory: ./Portfolio

      - name: Build the project
        run: npm run build --configuration=production
        working-directory: ./Portfolio

      - name: List build output
        run: ls -la ./Portfolio

      - name: Deploy files to server
        uses: appleboy/scp-action@master

        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          source: |
            ./Portfolio/dist/Portfolio/*
            ./Portfolio/db.json
          target: /var/www/Portfolio/Portfolio
          strip_components: 1

      - name: Restart Docker
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 2222
          script: |
            cd /var/www/Portfolio/Portfolio
            docker-compose down
            docker-compose up -d